---
title: "GitHub Actions e Ciencia de Dados"
subtitle: "Utilizando GitHub Actions para aproximar processos de CI/CD e Ciência de Dados"
author: "<br>Luis Henrique Zanandréa Paese<br>"
date: "<br>Setembro 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["style/shinobi.css", "ninjutsu", "style/ninpo.css"]
    self_contained: false
    nature: 
      ratio: "16:9"
      highlightStyle: monokai-sublime
      highlightLines: true
      countIncrementalSlides: false
      seal: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE, eval = T, warning = F, message = F, dev = 'svg')
```

class: middle bg-main1 hide-slide-number

.outline[
## Outline

* Introdução
* Revisitando Docker
* Ferramentas de CI/CD
* GitHub Actions
* Conclusão
* Live Demo
]

---
```{r Intro, child='sections/01_introduction.Rmd'}
```

```{r Why_Use, child='sections/02_revisiting_docker.Rmd'}
```

```{r How_To, child='sections/03_ci_cd_tools.Rmd'}
```

```{r Examples, child='sections/04_github_actions.Rmd'}
```

```{r Conclusions, child='sections/05_conclusion.Rmd'}
```

```{r Live_Demo, child='sections/06_livedemo.Rmd'}
```