class: bg-main1 split-30 hide-slide-number

.column.bg-main3[
]
.column.slide-in-right[
.sliderbox.bg-main2.vmiddle[
.font3[Introdução]
]]

---

class: middle center bg-main1 hide-slide-number

# O que é GitHub Actions?

--

  ## GitHub Actions é uma ferramenta desenvolvida pelo GitHub para prover uma infraestrutura de automação de workflow para testes, validações e deploys. 
  
--

  ## Ela visa fornecer um ambiente de fácil colaboração para que projetos open-source possam se valer de ferramentas de CI/CD
  
---

class: middle center bg-main1 hide-slide-number

# Como o GitHub Actions funciona?

--
  
  ## O GitHub Actions é composto basicamente de 3 componentes principais, _Workflows_, _jobs_, e _events_, que podem ser customizados de acordo com a necessidade do usuário. Visto que ele é uma ferramenta _event-driven_, o usuário pode configurar a execução de uma série de comandos após a ocorrência de um evento.
  
---

class: middle center bg-main1 hide-slide-number

# O que isso traz de diferente?

--
  <div class = "bullet2">
  <ul>
  <li> GitHub actions são basicamente diferentes execuções de <code class = "remark-inline-code">docker build</code> e <code class = "remark-inline-code">docker run</code>; </li>
  <li> Cada <em>action</em>, por padrão, roda isoladamente, facilitando o processo de debug; </li>
  <li> Marketplace de <em>actions</em> cresce de acordo com o uso da comunidade, dado que todo o processo é open-source; </li>
  </ul>
  </div>
  
---